### ISSUE TITLE
jQuery test failure after upgrading to Angular 1.4

### ISSUE THREAD

**Issue by robarchibald** [johnpapa/generator-hottowel#102]
I now receive this test error after upgrading to Angular 1.4.  Any thoughts on how to fix?

PhantomJS 1.9.7 (Windows 7 0.0.0) htSidebar directive:  when animating w/ jQuery fx off click triggers "when-done-animating" expression FAILED
        AssertionError: expected spy to have been called with arguments 42
            at C:/Projects/htAngular1.4/node_modules/chai/chai.js:873
            at C:/Projects/htAngular1.4/node_modules/sinon-chai/lib/sinon-chai.js:95
            at C:/Projects/htAngular1.4/node_modules/chai/chai.js:3627
            at C:/Projects/htAngular1.4/src/client/app/layout/ht-sidebar.directive.spec.js:116

**Comment by robarchibald** [comment]
Hmm, I was able to fix it when I changed the directive binding in ht-sidebar.directive.js to be the following.  If only I understood why this worked.  It wouldn't work unless the whenDoneAnimating was in both the bindToController and scope.  Also, forgive my ignorance, but what is '&?' doing?

```javascript
    var directive = {
            bindToController: {
                whenDoneAnimating: '&?'
            },
            link: link,
            restrict: 'EA',
            controller: 'SidebarController',
            controllerAs: 'vm',
            scope: {
                whenDoneAnimating: '&?'
            }
        };

**Comment by johnpapa** [comment]
& is for the function. ? is for optional

**Comment by johnpapa** [comment]
should be resolved with recent commits
