### ISSUE TITLE
Running build version into Apache Sever

### ISSUE THREAD

**Issue by cabilluos** [johnpapa/generator-hottowel#106]
Hi.

I'm  trying to run the application into an apache server with a little problem in the navigation. The application is deployed successfully, but when I try to access one section using the browser url directly the server show a 404 error, and this happen with all routes. 

What I'm missing?

Best Regards,
Daniel

**Comment by u0m3** [comment]
This might be the issue: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

**Comment by johnpapa** [comment]
see that link in @u0m3 's note for how to configures your servers

**Comment by cabilluos** [comment]
Thanks you @u0m3 this work +1
