### ISSUE TITLE
Jasmine option

### ISSUE THREAD

**Issue by louiealmeda** [johnpapa/generator-hottowel#116]
I hope there would be an option to use Jasmine for this generator

**Comment by ssbrewster** [comment]
You could add jasmine to `karma.conf.js` and install [the karma-jasmin adapter](https://github.com/karma-runner/karma-jasmine). Dropping mocha would mean no server side tests so personally I would keep that in.

```
// frameworks to use
// some available frameworks: https://npmjs.org/browse/keyword/karma-adapter
frameworks: ['mocha', 'chai', 'sinon', 'chai-sinon', 'jasmine']
```

**Comment by johnpapa** [comment]
we use mocha, but feel free to change to jasmine.
