### ISSUE TITLE
Inconsistent IIFE

### ISSUE THREAD

**Issue by belchugov** [johnpapa/generator-hottowel#118]
This is probably the nerdiest issue. I found that there consistent usega of JavaScritp closer:
```javascript
(function() {
```

and 

```javascript
(function () {
```

Probably the one without the space after function is the right one based on [IIFE[Style Y010]](https://github.com/johnpapa/angular-styleguide#iife)

**Comment by rllola** [comment]
+1 and I don't think it is the nerdiest issue.

**Comment by johnpapa** [comment]
hehe ... yeah, i agree consistency is better. but im letting this go unless someone wants to PR

**Comment by belchugov** [comment]
I'm on it.
