### ISSUE TITLE
More Prerequisites

### ISSUE THREAD

**Issue by ersimont** [johnpapa/generator-hottowel#124]
I had to install 2 prerequisites that were not mentioned in the README (Python and Visual Studio). They were both for [`node-gyp`](https://github.com/nodejs/node-gyp#installation). Perhaps the README should mention that we must also install the prereqs for that package?

Also, this is not actionable but it may be interesting to note in case a pattern emerges: PhantomJS did not install properly during the first run. I had to re-install it before `gulp test` succeeded (with a simple `npm install phantomjs`).

**Comment by ssbrewster** [comment]
So you're on Windows? And are you running npm install through a proxy?

**Comment by gravidThoughts** [comment]
I have a few things to add here.
I have a windows box.
I did not use `chocolatey`, I used the installer from the NodeJS website. 

Are you saying that using `chocolatey` will install these dependencies? Or will it configure node-gyp to use a native build system other than Python/Visual Studio?

I had Python and Visual Studio 2013 installed.

Install failed for any node-gyp based package (`bufferutil` and `utf-8-validate`) on the basis that it could not find the related `*.vcxproj` file. Afterwards, running `npm install --msvs_version=2013` allowed `node-gyp`  to successfully build those packages.

I ran into an additional issue where postinstall failed for `optipng`, `jpegtran-bin`, and `gifsicle`. The output was the same for each:
```
> gifsicle@3.0.1 postinstall C:\dev\Angular Testing\node_modules\gifsicle
> node lib/install.js

  ‼ Redirected 10 times. Aborting.
  ‼ gifsicle pre-build test failed
  i compiling from source
  x Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff
prefix="C:\dev\Angular Testing\node_modules\gifsicle\vendor" --bindir="C:\dev
gular Testing\node_modules\gifsicle\vendor" && make install
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Googling `autoreconf`, it appears to be a *nix tool. I am unsure why this is executing on a Windows box.

Do we have to install [AutoConf for Windows](http://gnuwin32.sourceforge.net/packages/autoconf.htm)?

**Comment by ssbrewster** [comment]
I'm primarily on OSX but have run the generator on Windows. Most of the issues I had installing from Windows were proxy related and fixed with digitaldrummerj.me/proxy-configurations/

I didn't need to install Visual Studio I think. I haven't touched the Windows machine for a while so will give it another go and see if I get the same issues.
