### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ssbrewster** [johnpapa/generator-hottowel#132]
I think I have uncovered a security flaw that can be resolved with a simple mitigation in the code. I'm cautious about making a disclosure here so please let me know the correct contact details to discuss the issue, whether it is actually a problem and/or make a pull request with the resolution?

Thanks

**Comment by dalelotts** [comment]
I think a reasonable amount of time has passed without a response or fix so a PR would be helpful

**Comment by ssbrewster** [comment]
Yes I'll send through a PR

**Comment by ssbrewster** [comment]
Given that I haven't had a response I'm still not sure about how much information I should include in the PR/comments in code? I expect that it would be unlikely that a malicious user would inspect project structure to check if it was generated with hottowel but that could be a dangerous assumption. I can be vague or explicit, it would be good to have some guidance on this before making the PR.

**Comment by dalelotts** [comment]
Personally, I assume the black hat's already know about the vulnerability, so it is better to disclose as much detail as possible, and provide a PR, so everyone can verify that the security flaw is fixed. 

If there really is a security flaw I'd be uncomfortable with my code running since October without a patch.

**Comment by johnpapa** [comment]
please make a PR or let's close this

**Comment by ssbrewster** [comment]
ok will do

**Comment by ssbrewster** [comment]
I've raised a PR for this #174
