### ISSUE TITLE
npm ERR! code 1 when running: npm install -g generator-hottowel

### ISSUE THREAD

**Issue by maximusdm** [johnpapa/generator-hottowel#134]
hi there,
I followed the instructions from:
https://github.com/johnpapa/generator-hottowel
but I am getting the error below after running: npm install -g generator-hottowel

C:\JohnPapa\HotTowel>npm install -g generator-hottowel
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN install:commander@2.8.1 ENOENT: no such file or directory, rename 'C:\Users\USER001\AppData\Roaming\npm\node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\download\node
_modules\decompress\node_modules\decompress-tarbz2\node_modules\seek-bzip\node_modules\commander' -> 'C:\Users\USER001\AppData\Roaming\npm\node_modules\generator-hottowel\node_modules\commander'
npm WARN install:read-all-stream@2.2.0 ENOENT: no such file or directory, rename 'C:\Users\USER001\AppData\Roaming\npm\node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\github-
username\node_modules\got\node_modules\read-all-stream' -> 'C:\Users\USER001\AppData\Roaming\npm\node_modules\generator-hottowel\node_modules\read-all-stream'
commander@2.8.1 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\download\node_modules\decompress\node_modules\decompress-tarbz2\node_modules\seek-bzip\node_modules\commander
 -> node_modules\generator-hottowel\node_modules\commander
request@2.65.0 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\request -> node_modules\generator-hottowel\node_modules\request
seek-bzip@1.0.5 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\download\node_modules\decompress\node_modules\decompress-tarbz2\node_modules\seek-bzip -> node_modules\genera
tor-hottowel\node_modules\seek-bzip
decompress-tarbz2@1.0.2 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\download\node_modules\decompress\node_modules\decompress-tarbz2 -> node_modules\generator-hottowel\no
de_modules\decompress-tarbz2
decompress@1.0.7 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\download\node_modules\decompress -> node_modules\generator-hottowel\node_modules\decompress
read-all-stream@2.2.0 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\github-username\node_modules\got\node_modules\read-all-stream -> node_modules\generator-hottowel\node_m
odules\read-all-stream
got@2.9.2 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\github-username\node_modules\got -> node_modules\generator-hottowel\node_modules\got
- download@1.0.7 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\download
- github-username@1.1.1 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\github-username
- har-validator@2.0.2 node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\request\node_modules\har-validator
- bl node_modules\generator-hottowel\node_modules\yeoman-generator\node_modules\request\node_modules\bl
C:\Users\USER001\AppData\Roaming\npm
└── (empty)

npm ERR! code 1

Any ideas?
Thank you

**Comment by ssbrewster** [comment]
Have you run `npm cache clean` and then tried installing?

**Comment by maximusdm** [comment]
yes but got the same error. I ended up using a different sample application :) thanks though

**Comment by detj** [comment]
Got this error when only installing the `eslint@2.3.0`

**Comment by JavascriptMick** [comment]
I got this error attempting to install a package that was already installed using a link.  I found I needed to clean it out of /usr/local/lib/node_modules

**Comment by asthagaur3** [comment]
i also get the same error when i was running npm ls promzard, how i can solve this problem

**Comment by crejohnny07** [comment]
I also got the same error while installing node inspector.

**Comment by asthagaur3** [comment]
yes i got and i solved also but i didn't rememberhow i solve it.
sorry

**Comment by sachanacar** [comment]
@asthagaur3 thanks for the useful info

**Comment by angelxaces** [comment]
I got it with angular

**Comment by gloaec** [comment]
Well I don't know if this can help, but I had a similar problem trying to install the "codemirror" npm package. I figured out the  `└── (empty)`  and the `npm ERR! code 1` occurred because the package was designed to be installed as a dependency in your project. So all I had to do was to add the `--save` flag

     npm install <package> --save

Hope this helps. Cheers !

**Comment by tonandon** [comment]
As everyone else, I'm also not sure if this is your case, but for me, it happened because I was trying to install a new package as some other packages on the project were missing installation  after I **_git pulled_** the projects latest version.

I fixed it running:
`npm i`
and then npm installing the package I wanted with no error.

They probably had pending dependencies going on among them.

**Comment by barneygravel** [comment]
For me it was due to an unstable network connectivity.  Make sure you don't get disconnected and have a good network speed.

**Comment by LeoD-E1** [comment]
me ocurrio lo mismo con el paquete bcrypt, lo que hice fue quitarlo del package.json, volver a ejecutar "npm install", se instalaron los demas paquetes, luego instalar por separado bcrypt, y se instalo correctamente, no se el motivo del fallo principal

**Comment by maalos** [comment]
all coments: english
that one guy:
> me ocurrio lo mismo con el paquete bcrypt, lo que hice fue quitarlo del package.json, volver a ejecutar "npm install", se instalaron los demas paquetes, luego instalar por separado bcrypt, y se instalo correctamente, no se el motivo del fallo principal

**Comment by jamiesauve** [comment]
^ English translation:

The same thing happened to me with the bcrypt package, what I did was take it out of the package.json, run "npm install" again, the rest of the packages installed, then install bcypt separately, and it installed correctly, I don't know why it failed the first time
