### ISSUE TITLE
Convert angular directives into components

### ISSUE THREAD

**Issue by JahlomP** [johnpapa/generator-hottowel#140]
I was thinking with the release of angular v1.5.0 (http://angularjs.blogspot.com/2015/11/angularjs-15-beta2-and-14-releases.html), a branch will be created to use some of the features that comes wit it like components. When the version becomes stable, it could then be merged into the master. This will enable hottowel to be ready for angular2 and i also think the component feature is cool.

**Comment by johnpapa** [comment]
interesting idea ... what do you propose?

**Comment by JahlomP** [comment]
First of all, we can turn some parts into components by using angular.component.

**Comment by johnpapa** [comment]
Looking for help on this, if anyone is interested. But we need to get a design doc on it first to see what it would look like and backwards compat.
