### ISSUE TITLE
ngdoc gulp task should be baked in to hot towel

### ISSUE THREAD

**Issue by dkromp** [johnpapa/generator-hottowel#141]
Since jsdoc seems like the way to go, it would be nice if hot towel had a gulp task with docs generator baked in. I haven't gotten gulp-ngdoc working, but I've used angular-jsdoc and it seems to do the job. https://github.com/allenhwkim/angular-jsdoc

**Comment by Stwissel** [comment]
Create a pull request?

**Comment by johnpapa** [comment]
yep. if you want it, please make a PR :)
