### ISSUE TITLE
Gulp dependency?

### ISSUE THREAD

**Issue by blowsie** [johnpapa/generator-hottowel#152]
With a large amount of issues in the project being around gulp and the gulp dependencies, I wondered If gulp itself was needed at all?

Is there any tasks in this project where Gulp is a requirement? Or could we just use NPM?
If NPM fits, I'd happily spend some time trying to remove gulp from this project and create a pull request.

The point here is that NPM itself is perfectly capable of achieving lots of build orientated tasks.
http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/

With using NPM to manage the tasks, the project should see less issues around gulp and/or its dependencies (around 40% of the github project issues).

What are peoples opinions on this topic?

**Comment by johnpapa** [comment]
up to you, of course. i find value in gulp. but go for it
