### ISSUE TITLE
gulp test failed

### ISSUE THREAD

**Issue by ericsoucy** [johnpapa/generator-hottowel#154]
when I try gulp test on a generated project, I get
```
[10:16:23] Using gulpfile D:\angularjs-tests\hottowelgenapp\gulpfile.js
[10:16:23] Starting 'vet'...
[10:16:23] Analyzing source with JSHint and JSCS
[10:16:24] Starting 'clean-code'...
[10:16:24] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[10:16:24] Finished 'clean-code' after 36 ms
[10:16:24] Starting 'templatecache'...
[10:16:24] Creating an AngularJS $templateCache
[10:16:25] Finished 'templatecache' after 478 ms
[10:16:26] Finished 'vet' after 2.47 s
[10:16:26] Starting 'test'...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use
  server = new Server(config, [done])
  server.start()
instead.
08 02 2016 10:16:26.841:WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
08 02 2016 10:16:27.114:WARN [watcher]: Pattern "D:/angularjs-tests/hottowelgenapp/src/client/tests/server-integration/**/*.spec.js" does not match any file.
08 02 2016 10:16:27.253:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
08 02 2016 10:16:27.260:INFO [launcher]: Starting browser PhantomJS
08 02 2016 10:16:27.818:INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket /#5tbmzMKuOa_9OSblAAAA with id 81801882
PhantomJS 1.9.8 (Windows 7 0.0.0) AdminController "before each" hook for "should be created successfully" FAILED
        Error: [$injector:modulerr] Failed to instantiate module ng due to:
        TypeError: 'null' is not an object (evaluating 'this')
            at $$SanitizeUriProvider (D:/angularjs-tests/hottowelgenapp/bower_components/angular/angular.js:17276)
            at D:/angularjs-tests/hottowelgenapp/bower_components/bardjs/dist/bard.js:694
```

**Comment by ericsoucy** [comment]
it may be related to angularjs 1.5 that was out last friday (fev 5)

**Comment by kmorey** [comment]
I had the same problem and downgrading angular to 1.4.9 fixed it for me

**Comment by the-james-burton** [comment]
I agree and I've done a trivial PR https://github.com/johnpapa/generator-hottowel/pull/155.

Thanks for the solution!

**Comment by nuKs** [comment]
See this issue
https://github.com/angular/angular.js/issues/13794

For some reason, the bind polyfill provided in hottowel doesn't work anymore. I tried lodash polyfill and get the same issue. Upgrading to phantomjs2 did the trick.

I'll push a pull request this evening.

**Comment by nuKs** [comment]
I didn't have the time to test yet. The pull request will come once it's done.

In the meanwhile, this should do it :
https://github.com/nuKs/generator-hottowel/commit/0c013c7503a61e40f83c0bae734cc90d87c893e2

**Comment by NoellyB76** [comment]
Goodness, this has killed me for almost 2 days... FINALLY found this issue here.  Thanks, nuKs.

**Comment by xapou** [comment]
Thanks @nuKs, your solution works fine.

**Comment by johnpapa** [comment]
I've also noticed PhantomJS 2 seems to help.

Is this working for everyone? If so, does someone want to make a PR on this to fix it?

**Comment by nuKs** [comment]
You're welcome. Thanks for testing. I make a pull request with the fix right away.

**Comment by nuKs** [comment]
PR: https://github.com/johnpapa/generator-hottowel/pull/160

**Comment by johnpapa** [comment]
closed with https://github.com/johnpapa/generator-hottowel/pull/155
