### ISSUE TITLE
Unit testing exception handler

### ISSUE THREAD

**Issue by bampakoa** [johnpapa/generator-hottowel#157]
@johnpapa I noticed that the unit test of **exception-handler.provider.js**, does not check if the logger is called at all. Is there any specific reason for that?

Thanks

**Comment by johnpapa** [comment]
what do you mean "check"?

**Comment by bampakoa** [comment]
Shouldn't we test the call of logger function in the unit test? Something like:

`expect(logger).toHaveBeenCalled()`

**Comment by johnpapa** [comment]
ah, sure

im making a bunch of updates right now. but i'd love to see a PR for this

**Comment by bampakoa** [comment]
I tried to test it [inside ](https://github.com/johnpapa/generator-hottowel/blob/master/app/templates/src/client/app/blocks/exception/exception-handler.provider.spec.js#L61)the catch block, after the last expect statement, but I seems that it never reaches logger.error statement during testing. Is it possible that `$delegate(exception, cause) ` prevents it from that?

**Comment by bampakoa** [comment]
Closed in replace of PR #170.
