### ISSUE TITLE
gulp build failing

### ISSUE THREAD

**Issue by swapnilwadagave** [johnpapa/generator-hottowel#161]
After yo hottowel helloworld
run gulp build
It is thowing error like ''Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'null' is not an object (evaluating 'this')"

There is some problem with angular 1.5.o version it looks.

Can you check with this please?

**Comment by jbmcewan** [comment]
It appears to be PhantomJS related. Swap Chrome or Firefox in and the tests work.

**Comment by ismarslomic** [comment]
+1 to last comment and d7c2d02. This solved gulp test as well

**Comment by johnpapa** [comment]
yep, phantom
