### ISSUE TITLE
Generate sub module

### ISSUE THREAD

**Issue by louiealmeda** [johnpapa/generator-hottowel#162]
I think there should be a gulp task that will automatically generate a sub module something like
(in the directory where you want to create the module) `gulp module moduleName` then have some options if it is a directive, if it has a route etc.

Then the task will generate all the files needed for a module 
`moduleName.module.js`,
`moduleName.directive.js`,
`moduleName.controller.js`,
`moduleName.controller.spec.js`,
`moduleName.html`

then each file has contents already, the `IIFE` getting the module, set up specs.
example in module.js file

```
(function () {
    'use strict';

    angular.module('app.moduleName', [
        //dependencies
    ]);


})();

```

All that is left is for the developer to jump in and start using the module

possibly include the new module in the parent's module.js dependency?

What do you think? I'm willing to help in implementing this feature

**Comment by johnpapa** [comment]
that would be a yo sub generator. I am open to the idea.

**Comment by eknowles** [comment]
https://github.com/jshipster/generator-ng-super has already done this and it works well, would be great to work the two together

**Comment by summermick** [comment]
no, they dont
