### ISSUE TITLE
Is this still maintained? 

### ISSUE THREAD

**Issue by hermanocabral** [johnpapa/generator-hottowel#163]
Howdy,

I'm about to start a new angular 1 project and decided to give this a try after watching one of John's Pluralsight courses about gulp(awesome course btw @johnpapa), _but_ this project doesn't seem to be actively maintained anymore. Is that the case?

**Comment by the-james-burton** [comment]
Hi @hermanocabral, I have had good success with https://github.com/Swiip/generator-gulp-angular from @Swiip. That generator seems to be very close to the superb angular 1 style guide from @johnpapa and is actively maintained.

Hope that helps.

**Comment by johnpapa** [comment]
yes - it worked "as-is" but I went through and updated a bunch of dependencies to remove some warnings.
