### ISSUE TITLE
Gulp serve-dev not working

### ISSUE THREAD

**Issue by Chamlee** [johnpapa/generator-hottowel#187]

**Comment by hassanuos** [comment]
Facing the same issue...

![errore](https://user-images.githubusercontent.com/13483548/35526706-2cd981c6-054a-11e8-8c5b-0da36f2af32f.PNG)

**Comment by dashawk** [comment]
what version of gulp did you use?

if it is 4.0.0 then you should downgrade it to 3.9.1.

Hope this helps
