### ISSUE TITLE
Issue connecting to debugger

### ISSUE THREAD

**Issue by setuk** [johnpapa/generator-hottowel#19]
gulp serve-build --debug

results in

[gulp] [nodemon] v1.2.1
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: C:\Users\taylosim\testapp3\src\server/**/*
[gulp] [nodemon] starting `node true=5858 ./src/server/app.js`
[21:44:45] Starting BrowserSync on port 8001

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\taylosim\testapp3\true=5858'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

I didnt install node js from chocolatey on windows.
Other than this all instructs followed.
Any thoughts?

**Comment by johnpapa** [comment]
fixed in #30

**Comment by ismarslomic** [comment]
I think this issue needs to be reopened since merge in ca5488c did overwrite the fix
