### ISSUE TITLE
404 Page - When setting html5mode to false

### ISSUE THREAD

**Issue by dashawk** [johnpapa/generator-hottowel#200]
### Issue details

I have a fresh install of hottowel. Everything works as usual until I changed the html5mode to false since I will be using S3 to host my files. When I try to navigate to the root  page `/`,  I am redirected to 404 Page.

### Steps to reproduce/test case

Install a fresh project with `yo hottowel freshProject`. Run `gulp serve-dev` if it is working. If it works, change `html5mode(false)` from `blocks/router/router-helper.provider.js`. Run `gulp serve-dev` again.

### Please specify which version of `generator-hottowel`, node and npm you're running

- [x] generator-hottowel
- [ ] Node
- [ ] Npm

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] other _(please specify which)_

### Which gulp command are you running ?

gulp serve-dev

**Comment by sunilmunikar** [comment]
my solution is to redirect to root (/) when there is an empty route by adding this line of code $urlRouterProvider.when('', '/');  in configureStates function in router-helper.provider.js

**Comment by dashawk** [comment]
I also tried this, but I will lose the 404 page whenever there is an invalid route.

**Comment by dashawk** [comment]
I disabled the html5mode because when I uploaded it to s3 and serve it there, it will not show the other pages because S3 assumes that pages are folders and not routes.

**Comment by dashawk** [comment]
Never mind. I already figure it out.

If there is anyone who want the solution, just reopen this and i'll post it here.

**Comment by suraj740** [comment]
getting same problem, i want the solution please help me if possible,Thanks

**Comment by dashawk** [comment]
Hi @suraj740. Sorry for not posting the solution here. I should have posted it here anyway.

Here is my solution.

In the `src/client/app/core/core.route.js`, just change the otherwise into a callback function and add your redirection like this:
```js
routerHelper.configureStates(getStates(), function () {
	var redirects = '/404';
	if($state.current.url === '^') {
		redirects = '/dashboard';
	}
	return redirects;
});
```

**Comment by suraj740** [comment]
Thanks:) @dashawk

**Comment by moolbits** [comment]
For those that want to keep html5mode enabled as is, you can handle this in s3 by adding a redirect policy your bucket config and within the AWS Console or CLI. 

To do this in the AWS Console leave html5mode(true) enabled in your apps source code. Go to your bucket in the AWS Console, select your bucket, go to properties, static website hosting, add the following Redirect Rules: 

```
<RoutingRules>
  <RoutingRule>
    <Condition>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <HostName>www.example.com</HostName>
      <ReplaceKeyPrefixWith>#/</ReplaceKeyPrefixWith>
    </Redirect>
  </RoutingRule>
</RoutingRules>
```

 Point the router on s3 to your error document, for ex: `app/core/404.html`.

If your using a CloudFront distribution for https, caching, TLS etc., be sure to add the path to your custom error doc within the configuration for that as well and invalidate the cache, especially prudent in CloudFront when deploying updates to the app's core router config.
