### ISSUE TITLE
Transition superseded error after generating project

### ISSUE THREAD

**Issue by tanveerrafiqueIVL** [johnpapa/generator-hottowel#205]
### Issue details
After generating project I am getting this issue
Error: [unitSecurity Error] transition superseded
$get@http://localhost:3002/bower_components/angular-ui-router/release/angular-ui-router.js:2903:42
invoke@http://localhost:3002/bower_components/angular/angular.js:4842:16
createInjector/protoInstanceInjector<@http://localhost:3002/bower_components/angular/angular.js:4636:20
getService@http://localhost:3002/bower_components/angular/angular.js:4783:32
injectionArgs@http://localhost:3002/bower_components/angular/angular.js:4808:58
invoke@http://localhost:3002/bower_components/angular/angular.js:4834:18
createInjector/protoInstanceInjector<@http://localhost:3002/bower_components/angular/angular.js:4636:20
getService@http://localhost:3002/bower_components/angular/angular.js:4783:32
injectionArgs@http://localhost:3002/bower_components/angular/angular.js:4808:58
invoke@http://localhost:3002/bower_components/angular/angular.js:4834:18
createInjector/<@http://localhost:3002/bower_components/angular/angular.js:4645:45
forEach@http://localhost:3002/bower_components/angular/angular.js:357:11
createInjector@http://localhost:3002/bower_components/angular/angular.js:4645:3
bootstrap/doBootstrap@http://localhost:3002/bower_components/angular/angular.js:1838:20
bootstrap@http://localhost:3002/bower_components/angular/angular.js:1859:12
angularInit@http://localhost:3002/bower_components/angular/angular.js:1744:5
@http://localhost:3002/bower_components/angular/angular.js:32977:5
jQuery.Callbacks/fire@http://localhost:3002/bower_components/jquery/dist/jquery.js:3187:11
jQuery.Callbacks/self.fireWith@http://localhost:3002/bower_components/jquery/dist/jquery.js:3317:7
.ready@http://localhost:3002/bower_components/jquery/dist/jquery.js:3536:3
completed@http://localhost:3002/bower_components/jquery/dist/jquery.js:3552:2
 Possibly unhandled rejection: {}

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of `generator-hottowel`, node and npm you're running

- [0.4.1 ] generator-hottowel
- [6.9.4 ] Node
- [ 2.14.3] Npm

### Affected platforms

- [ ] linux
- [ ] windows
- [this ] OS X
- [ ] other _(please specify which)_

### Which gulp command are you running ?

gulp serve-dev

**Comment by mikemead** [comment]
I had the same issue and it was resolved by https://github.com/johnpapa/generator-hottowel/pull/203

**Comment by tanveerrafiqueIVL** [comment]
Thank you so much @mikemead, switching ui-router to 0.4.2 solved the issue.
