### ISSUE TITLE
[Wiredep] Exclude files from bower_components

### ISSUE THREAD

**Issue by dashawk** [johnpapa/generator-hottowel#213]
### Issue details

I wanted to exclude some css files which came from a bower package.

### Steps to reproduce/test case

I tried to exclude a css file like this in wiredep.

```js
gulp.task('wiredep', function () {
	log('Wiring the bower dependencies into the html');

	var wiredep = require('wiredep').stream;
	var options = config.getWiredepDefaultOptions();
	options.exclude = [config.bower.directory + 'toastr/toastr.css']; // This doesn't work
	...
```

### Please specify which version of `generator-hottowel`, node and npm you're running

- [x] generator-hottowel
- [ ] Node
- [ ] Npm

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] other _(please specify which)_

### Which gulp command are you running ?

```cli
gulp wiredep
```

**Comment by blowsie** [comment]
@dashawk you should be able to use the "main" approach to specify files 
```
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    },
    "font-awesome": {
      "main": [
        "css/font-awesome.css"
      ]
    }
  }
```

**Comment by dashawk** [comment]
Thanks for this @blowsie. I forgot about that feature in bower.
