### ISSUE TITLE
Mix Angular 1 app based on generator-hottowel with Angular 2 typescript based code?

### ISSUE THREAD

**Issue by adamlubek** [johnpapa/generator-hottowel#215]
Hi,
Here's more of a question rather than issues but here it is:
We've got a project that was built on generator-hottowel and we're looking to migrate to Angular 2 or at least use angular 2 for any new developments. We would like to use typescript but project is rather big and migrating everything to typescript with webpack isn't an option. Ideally we would like to keep existing code using ES5, angular 1.4 and gulp tasks but develop new code with typescript in Angular 2

We had a look at ngupgrade or things like https://github.com/marcoacevey/hottowel-webpack but it seems that such would require us to rewrite everything which again isn't an option, we would like to keep current js files intact.

Can anyone advise on good strategy to start using Angular 2 mixed with project generated using generator-hottowel?

**Comment by johnpapa** [comment]
i may create HT for the latest angular using its CLI, but i will wait on blueprints to do this
