### ISSUE TITLE
What's going on with the releases? No NPM updates?

### ISSUE THREAD

**Issue by dashawk** [johnpapa/generator-hottowel#217]
### Issue details

I am just wondering why the latest release in npm is still 0.5 even though there is already 0.11 release here? What's the point on releasing 0.11 and not update the npm as well?

### Please specify which version of `generator-hottowel`, node and npm you're running

- [x] generator-hottowel
- [ ] Node
- [x] Npm

**Comment by johnpapa** [comment]
may have been a mistake. i'll check
