### ISSUE TITLE
Can't explain how dashboard route is kicking in on application startup

### ISSUE THREAD

**Issue by nareshbhatia** [johnpapa/generator-hottowel#22]
There is a [known issue](https://github.com/angular/angular.js/issues/1213) with the angular-router whereby the the initial location change event is missed if `ng-view` is nested in a partial using `ng-include`. As far as I can tell, the same issue exists with the angular-ui-router. Hottowel generated apps don't seem to have this issue. I would  like to understand how Hottowel works around this issue. If it is a solid workaround and we are not masking the issue, then that's great. Otherwise I would like to see the code restructured to move the top-level `ui-view` up to `index.html`.

To reproduce the issue mentioned above, I replaced the `blocks.router` with a very simple router:

    /* app.route.js */
    (function() {
        'use strict';

        angular
            .module('app')
            .config(configRouter);

        configRouter.$inject = ['$stateProvider', '$urlRouterProvider'];

        /* @ngInject */
        function configRouter($stateProvider, $urlRouterProvider) {

            // For any unmatched url, redirect to /
            $urlRouterProvider.otherwise('/');

            $stateProvider
                .state('dashboard', {
                    url: '/',
                    templateUrl: 'app/dashboard/dashboard.html',
                    controller: 'DashboardController',
                    controllerAs: 'vm'
                })
                .state('admin', {
                    url: '/admin',
                    templateUrl: 'app/admin/admin.html',
                    controller: 'AdminController',
                    controllerAs: 'vm'
                });
        }
    })();

Since the sidebar is dependent on `blocks.router`, I hardcoded the links as follows:

    
    ...
    <li class="nlightblue fade-selection-animation current">
        <a href="#/">Dashboard</a>
    </li>
    <li class="nlightblue fade-selection-animation">
        <a href="#/admin">Admin</a>
    </li>
    ...

Now when the app comes up, the dashboard view is not rendered. You must click one of the sidebar links for the view to kick in.

**Comment by johnpapa** [comment]
when you inject and use the router  (whichever you use)  it avoids this problem.
