### ISSUE TITLE
Trying to understand the primary purpose of /src/server directory

### ISSUE THREAD

**Issue by nareshbhatia** [johnpapa/generator-hottowel#23]
Is it to support the development process or to provide a starting point for the real server? I feel that if we eliminate the server directory, the overall project structure can be simplified significantly (following the LIFT principle even further). Instead of

    src
    |--- client
    |    `--- app
    `--- server
          `--- ...

we could simply have

    src
    `--- app

To elaborate, if the purpose of the server is to help with the development process, it might be better to include it in the gulpfile, something like this:

    gulp.task('serve', function() {
        var express = require('express');
        var app = express();

        // Serve static content from the /src and /bower_components
        app.use('/', express.static(__dirname + '/src'));
        app.use('/bower_components', express.static(__dirname + '/bower_components'));

        var server = require('http').createServer(app);

        // Start listening
        server.listen(8080);
    });

On the other hand, if the purpose is to provide a starting point for a real server, then I feel that it should be a separate project and not intermingled with the client. We have found it to be much more beneficial to build/test the client and the server separately and bring them together (continuously) for integration tests. This approach enforces deeper thinking into the API design and also allows front-end and back-end teams to work more independently.

Anyway, just my thoughts. I am curious to know your thinking behind the current approach.

Thanks in advance for your time.

**Comment by nareshbhatia** [comment]
Here's another thought:

If the server directory is purely to support builds, it could be moved at the root level with a name like `build`, making the client available right at `src` level. The output of the build could go to a folder such as `dist`.

    root
    |--- src
    |     |--- app
    |     |--- ...
    |     `--- index.html
    |--- build
    |     `--- app.js
    `--- dist

**Comment by johnpapa** [comment]
Separating the node code and the client code is important, as in a real app you likely would deploy the node server to serve static assets and another node server(or multiple) for web api endpoints. Plus, development concerns are different, so I like keeping it separate

Good questions tho

**Comment by nareshbhatia** [comment]
Thanks for the clarification. I have gone ahead and made this change to my version of the template. `server` has been moved up to the root level and I am calling it `mock-server`. I have also created a separate project for the real server. This kind of cleans up the client directory structure quite a bit. You can check out this structure at
- https://github.com/archfirst/angular-template
- https://github.com/archfirst/node-rest-template

I would love your hear your feedback. Also, it would be great if hottowel can be configured for such variations.

One thing to note: when connecting to the real server, the client can no longer assume that the api is available at `/api`. To make this transition easier, I have created a constant that defines the full API url (see [core.constants.js](https://github.com/archfirst/angular-template/blob/master/src/core/core.constants.js)).
