### ISSUE TITLE
Environment configuration separation

### ISSUE THREAD

**Issue by yevk** [johnpapa/generator-hottowel#25]
Hi,

I'm using several environments for projects, such as dev, QA, preprod and production. Each has its own backend api server and other settings that are specific for each environment.

Currently, the config value is set in the core config file. Since that file is minified with the rest of the app, it's hard to change the configuration of the app on the fly. Also, each deployment of the app overwrites the config, so it has to be set before build for each environment.

I think a solution similar to web.config of ASP.NET would be great here. A file that can be updated after the application is built and without having to rebuild the app for each environment. This way the config file can be set once for each environment.

I was thinking about either using a json file that would load during application start or creating a file with a module and a value that is not minified during the build and would remain referenced as is so it can be changed on the server and not redeployed every time.

The first solution is a bit problematic since we don't have access to $http during config and the second one I'm not sure how to implement due to the complexity of the build process. Can't quite figure out how to tell gulp to inject the file but not alter it in any way.

What do you think?

**Comment by danwkennedy** [comment]
We do something similar. After some research, we found a gulp plugin that lets us create a constants file from a json file and inject it into the angular app. Here's the link: https://github.com/ajwhite/gulp-ng-config

This allows us to inject things like different themes for each environment, hosts for API's, and build/version information.

**Comment by rllola** [comment]
+1
I also used it to config my urls path and OAuth2 config depending if i am in dev or prod.

**Comment by danwkennedy** [comment]
As a further example, here's an example of the code we use:

gulpfile.js:
```
/**
 * Set up config constants in the Angular 
 */
gulp.task('ngConfig', function() {
    var appPath = config.client + 'app',
        buildInfo = {
            revision: {
                long: rev('long'),
                short: rev('short')
            },
            tag: rev('tag'),
            branch: rev('branch')
        };

        log('Injecting configuration values');

        return gulp
            .src(appPath + '/config.json')
            .pipe($.ngConfig('app.config', {
                environment: args.environment,
                constants: {
                    environment: args.environment,
                    buildInfo: buildInfo
                }
            }))
            .pipe(gulp.dest(appPath));
});
```

The build info and environment constants are common values that never change between environments.

The json file looks like:
```
{
   "prod": {
        "theme.config" : {
           // Theming for prod. We switch the colors around so it's easy to see
        }
  },
  "dev": {
        "theme.config" : {
           // Theming for dev. We switch the colors around so it's easy to see
        }
  },
  "stage": {
        "theme.config" : {
           // Theming for stage. We switch the colors around so it's easy to see
        }
  }
}
```

The generated file will have the following constants defined:
```
angular.module('app.config', [])
.constant('theme.config', {})
.constant('environment', "dev")
.constant('buildInfo', {"revision":{"long":"","short":""},"tag":"","branch":""});
```

We can then inject those constants into our Angular components and the file is minified with the rest of the project when we do a release build.

**Comment by sergproua** [comment]
I could not integrate ng-config into gulpfile.js tasks without a significant refactoring which I wanted to avoid so I can stay with this template. I came up with this approach. It does not require any additional npm packages and does the job done, do a release build by running `gulp build --production`. Not the most elegant but --stage and other profiles can be added rather easily.

I've added the following files
src/client/app/app.config.local.js
```javascript
(function () {
    'use strict';

    angular.module('app')
        .constant('environment', {
            api: 'http://localhost:12345'
        });

})();
```

src/client/app/app.config.prod.js
```javascript
(function () {
    'use strict';

    angular.module('app')
        .constant('environment', {
            api: 'http://api.myproduction.com'
        });

})();
```

gulpfile.js wiredep task. change javascript source set for production
```javascript
gulp.task('wiredep', function() {
    log('Wiring the bower dependencies into the html');

    var wiredep = require('wiredep').stream;
    var options = config.getWiredepDefaultOptions();

    // Only production environment if flag is enabled
    var configJs = args.production ? config.jsProd : config.js;  // <<<--- add this line 

    // Only include stubs if flag is enabled
    var js = args.stubs ? [].concat(configJs, config.stubsjs) : configJs;  // <<<--- change this line 

    return gulp
        .src(config.index)
        .pipe(wiredep(options))
        .pipe(inject(js, '', config.jsOrder))
        .pipe(gulp.dest(config.client));
});
```

gulp.config.js, added exclusion/inclusion of the config files
```
        // app js, with no specs
        js: [
            clientApp + '**/*.module.js',
            clientApp + '**/*.js',
            '!' + clientApp + '**/app.config.prod.js', // <<<--- add this line 
            '!' + clientApp + '**/*.spec.js'
        ],
        jsProd: [
            clientApp + '**/*.module.js',
            clientApp + '**/*.js',
            '!' + clientApp + '**/app.config.local.js',  // <<<--- add this line 
            '!' + clientApp + '**/*.spec.js'
        ],
```

**Comment by bartvanremortele** [comment]
I integrated gulp-ng-config aswell by adding the following gulp task:

```
gulp.task('environment-config', function() {
    log('Creating environment configuration');
    var isDev = true;
    if (args.production) {
        isDev = false;
    }
    createEnvironmentConfiguration(isDev);
});

function createEnvironmentConfiguration(isDev) {
    var env = 'development';
    if (!isDev) {
        env = 'production';
    }

    return gulp
        .src('environment.config.json')
        .pipe($.ngConfig('environment.config', {
            environment: env,
            wrap: true
        }))
        .pipe(gulp.dest(config.appdirectory));
}
```

and a environment.config.json in the root of my application:
````
{
    "development": {
        "ENV_CONFIG": {
            "baseURI": "http://localhost:3000",
            "baseAPI": "http://localhost:3000/api/"
        }
    },
    "production": {
        "ENV_CONFIG": {
            "baseURI": "http://mydomain.com",
            "baseAPI": "http://api.mydomain.com"
        }
    }
}
```

I also had to add the follwoing to the config:

Ignore the generated environment.config.js when vetting
```
 alljs: [
            './src/**/*.js',
            './*.js',
            '!' + clientApp + 'environment.config.js'
        ],
```
explicitly pickup the generated file
```
// app js, with no specs
        js: [
            clientApp + 'environment.config.js',
            clientApp + '**/*.module.js',
            clientApp + '**/*.js',
            '!' + clientApp + '**/*.spec.js'
        ],
```

**Comment by nbcormier** [comment]
In practice, do you call your ng-config task as a dependency to another task?  Or do you run the ng-config task explicitly on the command line before doing a serve or build?

**Comment by johnpapa** [comment]
Is there an action for this? If so, please make a PR or let's close it
