### ISSUE TITLE
Tests require BardJS

### ISSUE THREAD

**Issue by technoSpino** [johnpapa/generator-hottowel#32]
When initially running gulp test I get the error 
```ReferenceError: Can't find variable: bard```

I had to manually copy and paste the bard.js file from its repo. I may have done something wrong or the documentation is missing a step. Either way I wanted to give you a heads up.

**Comment by johnpapa** [comment]
hmmmm. let me try that.

**Comment by johnpapa** [comment]
im not getting that error using `generator-hottowel@0.2.1`

**Comment by technoSpino** [comment]
Turns out it was an old version of bower getting in the way. I upgraded and cleaned bower cache. All works now. Sorry for the confusion

**Comment by johnpapa** [comment]
ok, thanks
