### ISSUE TITLE
Webstorm 9x Live Edit & Debug Support

### ISSUE THREAD

**Issue by dotnetrules** [johnpapa/generator-hottowel#37]
G'Day John, I followed your post on No-Sudo, configured as instructed, then installed generator-hottowel, all works great from terminal using gulp tasks etc, however my IDE on OSX is the latest version/build of WebStorm 9 and I think you sometimes use this too. Anyhow.... I can't seem to use the debugger or live edit in webstorm with hottowel, either the debugger icon is disabled or when I run the app via webstorm (not gulp) the hottowel page does not render, blank page, just some unstyled text title like "Hot Towel". Could gulp be getting in the way? I'm not looking to build at present, I just want to develop views, controllers etc and run/debug from webstorm. Any thoughts? Cheers Paul

**Comment by johnpapa** [comment]
Gulp is not getting in the way, in fact you can remove gulp and I bet you have the same problems.

It depends on how you run it. WebStorm needs to know what server to crank up to run the web pages. If you just run the html page in WebStorm, that wont work as it needs to talk to a back end. Gulp ranks up the back and and the views it in the browser. 

You could use WebStorm's support for gulp and create a gulp configuration. That will allow it to crank up the node server and the html page.

Enjoy!
