### ISSUE TITLE
Running build on a server

### ISSUE THREAD

**Issue by msutandi** [johnpapa/generator-hottowel#40]
Hi, this is probably a simple question, but i am obviously missing something here.  My understanding is that when i do a 'gulp serve-build' the app runs from the optimized files in the build folder.  So my assumption is that if i do a 'gulp build' that i should be able to copy the contents of the build folder and put that on another web server.  however when i do that, all that gets served up is an un-styled page with my apps name. what am i missing here? thanks!

**Comment by johnpapa** [comment]
gulp build is a dependency of gulp serve-build. The former puts everything in the build folder. The latter then adds the step of serving it.

There is not gulp task for copying to another web server, as there is no way to know where that may be.
