### ISSUE TITLE
Wrong path with serve-build

### ISSUE THREAD

**Issue by papo2608** [johnpapa/generator-hottowel#45]
If I execute the serve-build task the app starts with the wrong path (http://localhost:3000/ & dev index.html) and not (http://localhost:3000/build), but the files in the build folder are generated correctly.

Am I doing something wrong?

//EDIT: The problem is that the node server was started before for a dev build and so I got an EADDRINUSE error. Killing the process helps.

**Comment by johnpapa** [comment]
it should not be going to /build in the address bar. the port 3000 is the proxy for browserSync.

you may have had the dev served and not shut down properly, as you noted in the edit.
