### ISSUE TITLE
Bug fonts

### ISSUE THREAD

**Issue by papo2608** [johnpapa/generator-hottowel#46]
Change 
fonts: directory + 'font-awesome/fonts/*.*',
to
fonts: bower.directory + 'font-awesome/fonts/*.*',
in gulp.config.js to get fonts working on build-version.

**Comment by johnpapa** [comment]
this was fixed in the last build a few days ago in 0.2.5.  have you tried that?

**Comment by papo2608** [comment]
Thank you, works with 0.2.5.
