### ISSUE TITLE
Menu Design - Support Minimize to Icons Only and Sub Menues

### ISSUE THREAD

**Issue by ChrisHolcomb** [johnpapa/generator-hottowel#55]
John, thank you for this template to start new projects. I have just switched one of my apps over to use this structure and the modules you have implemented. This will defiantly make the project easier to work on for a team environment.

Could you help with creating a more friendly menu and navigation structure. I need sub menus and the ability to toggle the menu to show icons only so it doesn't take up so much real estate like this angular bootstrap theme ( http://themicon.co/theme/angle/v2.1.1/backend-angular/#/app/dashboard ).

I have manage to get the sub menus to work but feel it was a bit of a hack way to do it and would love to see how you would do it with this setup, still keeping the navigation dynamic by reading the $state config.

**Comment by johnpapa** [comment]
great ideas. but the menu is just a simple starting point. feel free to modify as needed.

always open to PRs, but it would require a lot of testing too for this
