### ISSUE TITLE
Better gulpfile proposition

### ISSUE THREAD

**Issue by rllola** [johnpapa/generator-hottowel#61]
Hello,

I want to say that I really like the generator-hottowel project because I believe that we miss a good angular generator (I have been using yeoman and I think it need some improvement).

I also think it hard to configure gulp when it has been generated. The file is really huge and contains many function. So my proposition is to seperate the tasks in a 'task' directory like it has been done in this repesitory : 
https://github.com/pickygoat/picky-gulp

Please, let me know your thought on this.

**Comment by johnpapa** [comment]
I tried separating all of the gulp tasks out into files and at first I liked it, but it quickly became a pain to find things as I often wanted to jump between tasks and functions. It certainly could be something you could do, until I find the right combination I prefer keeping one file for gulp and grunt.
