### ISSUE TITLE
shell.controller.spec.js test appears to fail?

### ISSUE THREAD

**Issue by TimDMorris** [johnpapa/generator-hottowel#66]
Hi sorry if this is a dumb question but I'm fairly new to all this and I've not done anything with karma or PhantomJS before.

When I build a new project from the generator and then run the tests I see a couple of failures that look like they come from shell.controller.spec.js, specifically:

```javascript
        it('should show splash screen', function () {
            expect(controller.showSplash).to.be.true;
        });

        it('should hide splash screen after timeout', function (done) {
            $timeout(function() {
                expect(controller.showSplash).to.be.false;
                done();
            }, 1000);
            $timeout.flush();
        });
```

These seem to error:

PhantomJS 1.9.8 (Windows 7) ShellController Shell controller should show splash screen FAILED
PhantomJS 1.9.8 (Windows 7) ShellController Shell controller should hide splash screen after timeout FAILED

When I look at shell.controller.js this looks as though these values are not being set on the controller but rather on the $rootScope e.g.

Ln 14

```javascript

        $rootScope.showSplash = true;

```

Ln 31

```javascript

        $rootScope.showSplash = false;

```

I'm fairly new to git as well unfortunately, but as far as I can make out these changes went in as part of [Merge pull request #53](https://github.com/johnpapa/generator-hottowel/commit/5a212662b5e371cce9ca80da909d1ad51eabdeb1)

I assume the flags have been moved to global scope because that makes them easier to get at from other places? but as far as what to do after that I'm out of my depth....

Guess I need to go read up about karma test specs and global scope

**Comment by johnpapa** [comment]
this was fixed in a recent release.

**Comment by TimDMorris** [comment]
Well like I say I'm still pretty new to this, but it does "look" like the code that's currently at the top level in:

generator-hottowel/app/templates/src/client/app/layout/shell.controller.js

is setting showSplash on the $rootScope 

this update looks like it was made 24 days ago.

While:

generator-hottowel/app/templates/src/client/app/layout/shell.controller.spec.js

looks like it is testing controller.showSplash, this spec file looks like it hasn't been updated since 22 Dec.

Currently in my local project created from the generator a couple of days back I've hacked the shell.controller.spec.js to also reference $rootScope.showSplash and the tests now pass for me locally, but I would be hesitant to submit this as a fix....  mainly because I'm new to all of this stuff and I keep reading people's blogs which say don't put stuff directly onto $rootScope if you can avoid it.

I'm currently tinkering with using a value provider to hold the showSplash flag but I'm not sure where it's best to actually declare this within the project structure...

Like I say I'm pretty new to this and might just currently be firmly grasping the wrong end of the stick with both hands.

**Comment by learningjs** [comment]
Uhm, cloned today and still get that error... !?!
