### ISSUE TITLE
Question about ng-annotate ?

### ISSUE THREAD

**Issue by Stamy** [johnpapa/generator-hottowel#68]
I was wondering why there are `$inject` defined everywhere and then the `/* @ngInject */` statement used. As I understand the whole point of using `/* @ngInject */` is to generate that for you right ? So why they are defined manually everywhere ?

    logger.$inject = ['$log', 'toastr'];

    /* @ngInject */
    function logger($log, toastr) {})

**Comment by johnpapa** [comment]
The manual injections can be removed or the comments. I included so folks could choose.

**Comment by Stamy** [comment]
Thanks for explaining. It would be good to see things like these in readme somewhere.
