### ISSUE TITLE
Update / Fix package.json or gulpfile

### ISSUE THREAD

**Issue by ChrisHolcomb** [johnpapa/generator-hottowel#70]
I just installed the latest version and tried to run gulp build and gulp serve-dev and had a lot of dependency issues. I was able to get rid of most of them by running npm install on the missing packages but this last one I can't seem to get:

Error: Cannot find module 'caniuse-db/data'

**Comment by scubaworks** [comment]
I am having this issue as well.

**Comment by johnpapa** [comment]
prob a hiccup a the time from npm
