### ISSUE TITLE
Build version does not load js/app.js or styles/app.css

### ISSUE THREAD

**Issue by ditadi** [johnpapa/generator-hottowel#71]
Hello John,

Thanks for the great template.  I've ran into issues when using >>gulp serve-build, minified app.js and app.css files aren't loading.  The fix for this would be editing generator-hottowel/app/templates/src/client/_index.html L20 and L45, we simply need to add a space after the minified file name otherwise it thinks that --> is part of the file name.

 
 

Thanks,
Dmitriy

**Comment by EnterpriseWide** [comment]
i have added a pull request for this. Thanks Dmitriy, good find.
https://github.com/johnpapa/generator-hottowel/pull/75

**Comment by johnpapa** [comment]
thanks, merged and closed
