### ISSUE TITLE
gulp-ng-annotate failed

### ISSUE THREAD

**Issue by misseur** [johnpapa/generator-hottowel#73]
I've just tried to test your generator, and i've seen that "optimize" doesn't work for me.

[18:31:22] gulp-inject 1 files into index.html.
C:\Users\Alliance\Desktop\wwtest\node_modules\gulp-ng-annotate\node_modules\ngannotate\build\es5\ng-annotate-main.js:330
    target.$methodName = method.name;
                       ^
TypeError: Cannot assign to read only property '$methodName' of false

i'm on window 8 64b with npm 2.7.4 and node 0.12.2

It seem that gulp-ng-annotate doesn't have the good version of no-annotate.

Just need to upgrade guld-ng-annotate to 0.5.2.

**Comment by johnpapa** [comment]
now upgraded
