### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by EnterpriseWide** [johnpapa/generator-hottowel#77]
I am planning to build an authentication mechanism for an app i am building.
does any implementation exist that shows a working mechanism built into a hottowel app that I can use as a reference
is https://github.com/johnpapa/ng-demos/tree/master/ng-jwt any good for this

**Comment by EnterpriseWide** [comment]
is the hottowel a better place to start than ng-demos/modular?

**Comment by ChrisHolcomb** [comment]
I have a similar question. I have JWT's going with an ASP.NET Web API backend and an AuthInterceptor factory on the angular side. Currently for testing I am just showing and hiding the login screen on the dashboard based on the authentication. I would prefer to have a separate page without the top banner or menu bar, what would be the best way to handle this with the current model and keeping to the rest of your best practices?

**Comment by EnterpriseWide** [comment]
I Seem to be in the situation. I can swing when it comes to backend but the front end is something I am still learning. I am planning to jam some more time into it this weekend. John and ward bell both look like they would be willing to review progress and help you plan if you actually do a plan in a doc and share it with them. I think I a just going to try submitting some pr's for bits and pieces and do it that way while I continue to build out the rest of my app. I reckon you should do a pr with your bits and pieces and John will make sure it all comes together in the planning

**Comment by ChrisHolcomb** [comment]
This was my solutions. On the "shell.controller.js" file in the activate function I check to see if the $rootScope.userProfile (which gets set from my dataservice call on a successful login) is undefined and if so redirect to a login screen, if not then call the getNavRoutes() function to show the menu items and $state.go('dashboard') to go to the dashboard screen.

**Comment by johnpapa** [comment]
there are patterns for securing your app, patterns for getting claims, patterns for showing routes ... not really somethign i want in a simple generator. But i may blog about it sometime
