### ISSUE TITLE
Please don't recommend `maximum-scale=1.0` and `user-scalable=no`

### ISSUE THREAD

**Issue by dmitriz** [johnpapa/generator-hottowel#80]
The index file
https://github.com/johnpapa/generator-hottowel/blob/master/app/templates/src/client/_index.html
recommends to block the user from zooming by means of these declarations:

      <meta name="viewport" content="..., maximum-scale=1.0, user-scalable=no"/>

**Please don't!**

I have bad eyes and find it really frustrating when sites silently block my attempts to zoom, in order to read them more comfortably for my eyesight. The designer may think the site looks perfect but the user will suffer and leave it for ones who care.

Please read here if this is still not convincing:

http://stackoverflow.com/a/30044183/1614973
http://blog.javierusobiaga.com/stop-using-the-viewport-tag-until-you-know-ho
http://www.lukew.com/ff/entry.asp?1945
http://ux.stackexchange.com/questions/37511/should-users-be-able-to-zoom-in-a-responsive-webdesign

**Comment by johnpapa** [comment]
great points. im always open to PRs and tests for them
