### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lswith** [johnpapa/generator-hottowel#90]
I was hoping you could add support for a typescript environment?

**Comment by johnpapa** [comment]
coming soon

**Comment by wiredprogrammer** [comment]
I'd love to see this too.  I'm struggling to convert the template to typescript at the moment.  The TypeScript for Large AngularJS applications by Justin Schwartzenberger on pluralsight is helping a lot but I'm so new to both angular and typescript that I'd love to see a conversion by people with more experience than I.

**Comment by cgsainty** [comment]
I would also really like to see this happen

**Comment by Ledragon** [comment]
I just posted a blog post about converting the app to TypeScript: http://wp.me/p5ZQ8p-2U
If that may be of any help... Second part coming soon

**Comment by zarusz** [comment]
Any news on adding TypeScript support? It's mid 2016 already ;)

**Comment by johnpapa** [comment]
this is not going to happen in this hottowel. feel free to fork
