### ISSUE TITLE
Question - How to Add Web API Backend?

### ISSUE THREAD

**Issue by jkruer01** [johnpapa/generator-hottowel#98]
Hey John,

First I want to say that I love your Pluralsight Courses.  Also, thanks for all of your hard work on the Hottowel project.  I finally got it working.  I just installed the generator locally instead of using the -g option.  I still don't know why that isn't working.

Anyways, I know that this isn't the right place to ask but I didn't know where else to go.  I have used your generator-aspnet to crease a Web API project, and I have used your generator-hottowel to make an angular project.  What is the easiest way to make these two work together? I want a single project that has the hottowel angular for the front end and the web api controllers for the back-end.  What is the best way to approach this?

Ideally I would like to get this project deployed to either Digital Ocean or Azure Ubuntu vm.

I'm new to the whole yeoman and linux world.  I'm coming from a Visual Studio/Windows world.

Thanks!
Jeremy

**Comment by johnpapa** [comment]
you can deploy anywhere. pick any back end you want.

yes, really more of a StackOverflow question
