### ISSUE TITLE
exceptionHandlerProvider test broken

### ISSUE THREAD

**Issue by annechinn** [johnpapa/generator-hottowel#99]
This test is passing, but is testing the wrong item. It should be testing exceptionHandlerProvider. 

describe('$exceptionHandler', function() {
        it('should have a dummy test', inject(function() {
            expect(true).to.equal(true);
        }));

        it('should be defined', inject(function($exceptionHandler) {
            expect($exceptionHandler).to.be.defined;
        }));

        it('should have configuration', inject(function($exceptionHandler) {
            alert($exceptionHandler.config);
            expect($exceptionHandler.config).to.be.defined;
        }));

**Comment by johnpapa** [comment]
wanna make a PR?

**Comment by johnpapa** [comment]
someone pr'd it
